version: '3'

services:
  app:
    build: .
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      - NODE_ENV=production
      - SERVER_PORT=${SERVER_PORT}
      - PG_USER=postgres
      - PG_DB=postgres
      - PG_PW=123456
      - PG_PORT=5432
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: