version: "3"

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - db
    restart: on-failure

  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PW}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - ${PG_PORT}:${PG_PORT}

volumes:
  pgdata: