version: "3"

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "3001:3001"
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
